CATALOGUE_HOST: catalogue.backend-{{ env }}.devopspract.site #here cart directly cannot connect catalogue, everything will happen through ALB so need to give like .backend-{{ env }}
REDIS_HOST: redis-{{ env }}.devopspract.site